
default-breakpoint: 100
default-pattern: "\\b((https|http?|ftp|file)://[-a-zA-Z\\d+&@#/%?=~_|!:,.;]*[-a-zA-Z\\d+&@#/%=~_|])"

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:

server:
  servlet:
    context-path: /webtools
  port: 9090
